import os
import smtplib
import json
from pathlib import Path
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def load_dotenv_file():
    env_path = Path(__file__).resolve().parent.parent / ".env"
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def get_env_int(name, default):
    try:
        return int(os.getenv(name, default))
    except (TypeError, ValueError):
        return int(default)


load_dotenv_file()

EMAIL_CONFIG = {
    "smtp_host": os.getenv("SMTP_HOST", "smtp.gmail.com"),
    "smtp_port": get_env_int("SMTP_PORT", 587),
    "sender": os.getenv("EMAIL_SENDER", ""),
    "password": os.getenv("EMAIL_PASSWORD", ""),
    "recipient": os.getenv("EMAIL_RECIPIENT", "")
}


def build_email_content(phase3_results):
    lines = []

    lines.append("🚀 AI JOB PIPELINE RESULTS")
    lines.append("")
    total_jobs = 0

    for company_data in phase3_results:
        total_jobs += len(company_data["jobs"])
    lines.append(f"Total Jobs Found: {total_jobs}")
    lines.append("")

    for company_data in phase3_results:
        company = company_data["company"]
        lines.append("━━━━━━━━━━━━━━━━━━")
        lines.append(f"🏢 {company}")
        lines.append("━━━━━━━━━━━━━━━━━━")

        for job in company_data["jobs"]:
            title = job.get("title", "Unknown Role")
            location = job.get("location", "Unknown")
            experience = job.get("experience","Not Mentioned")
            lines.append("")
            lines.append(f"💼 {title}")
            lines.append(f"📍 {location}")
            lines.append(f"🧠 {experience}")
            lines.append("\n")
            job_url = job.get("job_url")

            if job_url:
                lines.append(f"🔗 {job_url}")
            reddit_intel = job.get("reddit_intel","")

            if reddit_intel:
                lines.append("")
                lines.append("📊 MARKET INTEL")
                lines.append(str(reddit_intel))

            lines.append("")
            lines.append("──────────────────")
        lines.append("")
    lines.append("")
    lines.append("Generated by AI Job Pipeline")
    return "\n".join(lines)


def is_email_configured():
    return all([
        EMAIL_CONFIG["sender"],
        EMAIL_CONFIG["password"],
        EMAIL_CONFIG["recipient"]
    ])


def send_email(phase3_results):
    if not is_email_configured():
        print("\nEMAIL NOT SENT: missing email configuration.")
        print("Set EMAIL_SENDER, EMAIL_PASSWORD, and EMAIL_RECIPIENT in .env or environment.")
        return

    content = build_email_content(phase3_results)
    msg = MIMEMultipart()
    msg["From"] = EMAIL_CONFIG["sender"]
    msg["To"] = EMAIL_CONFIG["recipient"]
    msg["Subject"] = "AI Job Pipeline Results"
    msg.attach(MIMEText(content, "plain"))
    try:
        server = smtplib.SMTP(EMAIL_CONFIG["smtp_host"], EMAIL_CONFIG["smtp_port"])
        server.starttls()
        server.login(EMAIL_CONFIG["sender"], EMAIL_CONFIG["password"])
        server.send_message(msg)
        server.quit()
        print("\nEMAIL SENT SUCCESSFULLY")
    except Exception as e:
        print("\nEMAIL FAILED")
        print(e)